### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by laleeroy** [joshuous/aosp-missing-blobs#8]
Is it possible if we search recursively but only for specific blobs? 
Eg. I only want to print out what's needed by android.hardware.radio.config@1.0.so

**Comment by joshchoo** [comment]
Would the most straightforward solution be to pipe the results to grep?

```
asop-missing-blobs ... | grep android.hardware.radio.config@1.0.so
```

**Comment by laleeroy** [comment]
Thank you very much for the quick response! 👍🙂
